replicaCount: 1
namespace: monitoring

image:
  repository: us-east1-docker.pkg.dev/sre-sandbox1/observability-tools/connector_metrics
  pullPolicy: IfNotPresent
  tag: 1.0.4

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10

readinessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: 
  app: connector-metrics

service:
  type: ClusterIP
  port: 9137
  targetPort: 9137

resources: 
  limits:
    cpu: 20m
    memory: 50Mi
  requests:
    cpu: 10m
    memory: 30Mi

prometheus:
  url: http://prometheus-kube-prometheus-prometheus:9090/api/v1/query

secrets:
  name: connectormetrics-statuspage-secrets

configMap:
  queries:
    - metric_id: "7x111tyw0q53"
      query: 'avg(probe_http_duration_seconds)'

ingress:
  enabled: false

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

volumes: 
- name: queries-volume
  configMap:
    name: connectormetrics-queries-config

volumeMounts:
- name: queries-volume
  mountPath: /app/src/queries.yaml
  subPath: queries.yaml

nodeSelector: 
  cloud.google.com/gke-nodepool: pool-hubble

tolerations: []

affinity: {}

serviceMonitor:
  enabled: true