apiVersion: v1
kind: Service
metadata:
  name: {{ include "connector-metrics.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "connector-metrics.fullname" . }}
    {{ include "connector-metrics.labels" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: metrics
  selector:
    app: {{ include "connector-metrics.fullname" . }}