apiVersion: apps/v1
kind: Deployment
metadata:
  name: connector-metrics
  namespace: hubble
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connector-metrics
  template:
    metadata:
      labels:
        app: connector-metrics
    spec:
      containers:
      - name: connector-metrics
        image: us-east1-docker.pkg.dev/sre-sandbox1/observability-tools/connector_metrics:1.0.3
        env: 
        - name: PROMETHEUS_URL
          value: http://prometheus-kube-prometheus-prometheus:9090/api/v1/query
        - name: STATUSPAGE_API_KEY
          valueFrom:
            secretKeyRef:
              name: connectormetrics-statuspage-secrets
              key: STATUSPAGE_API_KEY
        - name: STATUSPAGE_PAGE_ID
          valueFrom:
            secretKeyRef:
              name: connectormetrics-statuspage-secrets
              key: STATUSPAGE_PAGE_ID
        ports:
        - containerPort: 9137
        volumeMounts:
        - name: queries-volume
          mountPath: /app/src/queries.yaml
          subPath: queries.yaml
        resources:
          limits:
            cpu: 500m
            memory: 400Mi
          requests: 
            cpu: 300m
            memory: 200Mi
      volumes:
      - name: queries-volume
        configMap: 
          name: connectormetrics-queries-config