apiVersion: v1
kind: Service
metadata:
  name: connector-metrics
  namespace: hubble
  labels:
    app: connector-metrics
spec:
  type: ClusterIP
  selector:
    app: connector-metrics
  ports:
    - name: metrics
      protocol: TCP
      port: 9137
      targetPort: 9137