apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: connector-metrics
  labels:
    app: connector-metrics
    release: prometheus
  namespace: hubble
spec:
  selector:
    matchLabels:
      app: connector-metrics
  endpoints:
  - interval: 30s
    port: metrics
    scheme: http
    path: /metrics
    scrapeTimeout: 29s
  namespaceSelector:
    any: true