apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.volume.configMap.name }}
  namespace: {{ .Values.namespace }}
data:
  queries.yaml: |
    promql:
{{- range .Values.configMap.queries }}
      - metric_id: {{ .metric_id }}
        query: '{{ .query }}'
{{- end }}